GET http://localhost:3000/milkyway/planets
################################################################
GET http://localhost:3000/milkyway/planets/1
################################################################
GET http://localhost:3000/milkyway/articles
################################################################
GET http://localhost:3000/milkyway/merch
################################################################