GET http://localhost:3000/milkyway/planets
################################################################
GET http://localhost:3000/milkyway/planets/1
################################################################